name: Daily AI Video

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama pull llama3 &
          sleep 30

      - name: Copy config
        env:
          CONFIG: ${{ secrets.CONFIG_JSON }}
        run: echo "$CONFIG" > config.json

      - name: Run main script
        run: python main.py
